package engine

import (
	"crypto/sha256"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"os"
	"testing"
)

func TestOriginalFlyingSchedules(t *testing.T) {
	loader, err := os.ReadFile("../../assets/unpacked/loader.bin")
	if os.IsNotExist(err) {
		t.Skip("extract the original ADF to verify its flying schedules")
	}
	if err != nil {
		t.Fatal(err)
	}
	overlays := map[string][]byte{}
	for _, name := range []string{"lods0f", "lodst1", "lodst2", "lodst3"} {
		overlays[name], err = os.ReadFile("../../assets/unpacked/" + name + ".bin")
		if err != nil {
			t.Fatal(err)
		}
	}
	schedules, err := NativeSchedules(loader, 0x100, overlays)
	if err != nil {
		t.Fatal(err)
	}
	for stage, count := range []int{169, 139, 161, 205} {
		if len(schedules[stage]) != count {
			t.Fatalf("stage%d has%d records; expected%d original records", stage, len(schedules[stage]), count)
		}
	}
	first := schedules[0][0]
	if first.Progress != 330 || first.X != 0 || first.Y != -32 || first.RandomMode != 1 || first.Definition.NativeKind != 1 || first.Definition.Width != 32 || first.Definition.Height != 32 {
		t.Fatalf("first original wave=%+v", first)
	}
	formation := schedules[0][3]
	if first.Definition.Score != 5000 {
		t.Fatalf("original packed decimal ship score=%d", first.Definition.Score)
	}
	if formation.Progress != 500 || formation.X != 288 || formation.Y != 20 || len(formation.Script) == 0 {
		t.Fatalf("first directed formation=%+v", formation)
	}
	motion := formation.Script[0]
	if motion.Duration != 40 || motion.VX != -4<<16 || motion.VY != 0 || motion.Frame != 12 {
		t.Fatalf("original formation first motion=%+v", motion)
	}
	if formation.RepeatScript {
		t.Fatal("the first original formation terminates with FF01")
	}
	scripted := 0
	for _, stage := range schedules {
		for _, event := range stage {
			if len(event.Script) != 0 {
				scripted++
			}
		}
	}
	if scripted < 100 {
		t.Fatalf("only%d original scripted formations were recovered", scripted)
	}
}

func TestOriginalBCDScore(t *testing.T) {
	for encoded, score := range map[uint16]int{0x0001: 1, 0x0100: 100, 0x1000: 1000, 0x5000: 5000, 0x9999: 9999} {
		if actual := DecodeBCDScore(encoded); actual != score {
			t.Fatalf("original score$%04x=%d;expected%d", encoded, actual, score)
		}
	}
}

func TestDirectionCommandTurnsAndLoops(t *testing.T) {
	// This fixture tests the original turn ordering: movement uses the old
	// direction, while the renderer uses the direction after this tick's turn.
	data := make([]byte, 256)
	base := uint32(0x1000)
	vectors := base
	for direction := 0; direction < 32; direction++ {
		binary.BigEndian.PutUint16(data[direction*4:], uint16(direction))
		binary.BigEndian.PutUint16(data[direction*4+2:], uint16(32-direction))
	}
	pointer := base + 128
	copy(data[128:], []byte{3, 0xe0, 1, 1, 0xff, 0, 0, 0, 0x10, 0x80})
	motions, loop, repeat, err := decodeDirectionScript(memory{data, base}, vectors, pointer)
	if err != nil {
		t.Fatal(err)
	}
	if !repeat || loop != 0 || len(motions) != 3 {
		t.Fatalf("original loop=%d repeat=%v motions=%v", loop, repeat, motions)
	}
	if motions[0].VX != 0 || motions[0].Frame != 0 || motions[1].VX != 64 || motions[1].Frame != 1 || motions[2].VX != 128 || motions[2].Frame != 1 {
		t.Fatalf("original turn ordering=%v", motions)
	}
}

func TestFlyingDecoderRejectsMissingOriginals(t *testing.T) {
	if _, err := NativeSchedules(nil, 0x100, nil); err == nil {
		t.Fatal("missing original schedule data was accepted")
	}
}

// The fingerprints are generated by the original 68000 direction handler,
// stopping before graphics. No second native movement decoder supplies them.
func TestDirectedFormationsAgainstOriginal68000(t *testing.T) {
	loader, err := os.ReadFile("../../assets/unpacked/loader.bin")
	if os.IsNotExist(err) {
		t.Skip("extract the original ADF to compare flight trajectories")
	}
	if err != nil {
		t.Fatal(err)
	}
	overlays := map[string][]byte{}
	for _, name := range []string{"lods0f", "lodst1", "lodst2", "lodst3"} {
		overlays[name], err = os.ReadFile("../../assets/unpacked/" + name + ".bin")
		if err != nil {
			t.Fatal(err)
		}
	}
	schedules, err := NativeSchedules(loader, 0x100, overlays)
	if err != nil {
		t.Fatal(err)
	}
	encoded, err := os.ReadFile("wave_oracle_test.json")
	if err != nil {
		t.Fatal(err)
	}
	var references []struct {
		Stage, Event, Ticks int
		Hash                string
	}
	if err = json.Unmarshal(encoded, &references); err != nil {
		t.Fatal(err)
	}
	if len(references) != 56 {
		t.Fatalf("original directed formation count=%d;expected56", len(references))
	}
	for _, r := range references {
		event := schedules[r.Stage][r.Event]
		x, y := int32(288<<16), int32(20<<16)
		trajectory := []byte{}
		index, remaining := 0, 0
		var motion Motion
		for tick := 0; tick < r.Ticks; tick++ {
			if remaining == 0 {
				if index == len(event.Script) {
					if !event.RepeatScript {
						t.Fatalf("stage%d event%d native script ended at tick%d,originalruns%d", r.Stage, r.Event, tick, r.Ticks)
					}
					index = event.ScriptLoop
				}
				motion = event.Script[index]
				index++
				remaining = motion.Duration
			}
			x += int32(motion.VX)
			y += int32(motion.VY)
			remaining--
			frame := make([]byte, 9)
			binary.BigEndian.PutUint32(frame, uint32(x))
			binary.BigEndian.PutUint32(frame[4:], uint32(y))
			frame[8] = byte(motion.Frame)
			trajectory = append(trajectory, frame...)
		}
		hash := fmt.Sprintf("%x", sha256.Sum256(trajectory))
		if hash != r.Hash {
			t.Fatalf("stage%d event%d native trajectory=%s;original=%s", r.Stage, r.Event, hash, r.Hash)
		}
	}
}
